name: Standards

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1,16 * *'

jobs:
  composer-validate:
    name: Validate composer.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: 7.4
          coverage: none

      - name: Validate composer.json
        run: composer validate --strict --no-check-lock

  cs-check:
    name: PHP Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: 7.4
          coverage: none

      - name: Install dependencies
        run: wget https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer.phar

      - name: Check CS
        run: php php-cs-fixer.phar fix --dry-run --diff
