name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1,16 * *'

jobs:
  symfony-version-tests:
    name: PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [7.2, 7.3, 7.4]
        symfony: [4.4.*, 5.0.*]

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-${{ matrix.php }}-${{ matrix.symfony }}-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: |
          composer global require --no-progress --no-scripts --no-plugins symfony/flex dev-master
          composer update --prefer-dist --no-interaction --no-suggest
          vendor/bin/simple-phpunit install
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}

      - name: Run tests
        run: vendor/bin/simple-phpunit -v

  dependency-version-tests:
    name: PHP ${{ matrix.php }} --${{ matrix.dependency-version }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [7.2, 7.3, 7.4]
        dependency-version: [prefer-lowest, prefer-stable]

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-${{ matrix.php }}-${{ matrix.dependency-version }}-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: |
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest
          vendor/bin/simple-phpunit install

      - name: Run tests
        run: vendor/bin/simple-phpunit -v

  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: 7.4
          coverage: xdebug

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-coverage-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction --no-suggest
          vendor/bin/simple-phpunit install

      - name: Run code coverage
        run: vendor/bin/simple-phpunit -v --coverage-text --coverage-clover=coverage.clover

      - name: Send code coverage
        run: |
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.clover
